// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.2
// source: proto/cli.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_cli_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_cli_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{1}
}

type RegisterWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	WorkspaceName string                 `protobuf:"bytes,3,opt,name=workspace_name,json=workspaceName,proto3" json:"workspace_name,omitempty"`
	LastHash      string                 `protobuf:"bytes,4,opt,name=last_hash,json=lastHash,proto3" json:"last_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkspaceRequest) Reset() {
	*x = RegisterWorkspaceRequest{}
	mi := &file_proto_cli_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkspaceRequest) ProtoMessage() {}

func (x *RegisterWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterWorkspaceRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterWorkspaceRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterWorkspaceRequest) GetWorkspaceName() string {
	if x != nil {
		return x.WorkspaceName
	}
	return ""
}

func (x *RegisterWorkspaceRequest) GetLastHash() string {
	if x != nil {
		return x.LastHash
	}
	return ""
}

type RegisterWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkspaceResponse) Reset() {
	*x = RegisterWorkspaceResponse{}
	mi := &file_proto_cli_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkspaceResponse) ProtoMessage() {}

func (x *RegisterWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{3}
}

type RegisterUserToWorkspaceRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ListenerUsername       string                 `protobuf:"bytes,1,opt,name=listener_username,json=listenerUsername,proto3" json:"listener_username,omitempty"`
	ListenerPassword       string                 `protobuf:"bytes,2,opt,name=listener_password,json=listenerPassword,proto3" json:"listener_password,omitempty"`
	WorkspaceName          string                 `protobuf:"bytes,3,opt,name=workspace_name,json=workspaceName,proto3" json:"workspace_name,omitempty"`
	WorkspaceOwnerUsername string                 `protobuf:"bytes,4,opt,name=workspace_owner_username,json=workspaceOwnerUsername,proto3" json:"workspace_owner_username,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterUserToWorkspaceRequest) Reset() {
	*x = RegisterUserToWorkspaceRequest{}
	mi := &file_proto_cli_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserToWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserToWorkspaceRequest) ProtoMessage() {}

func (x *RegisterUserToWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserToWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserToWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterUserToWorkspaceRequest) GetListenerUsername() string {
	if x != nil {
		return x.ListenerUsername
	}
	return ""
}

func (x *RegisterUserToWorkspaceRequest) GetListenerPassword() string {
	if x != nil {
		return x.ListenerPassword
	}
	return ""
}

func (x *RegisterUserToWorkspaceRequest) GetWorkspaceName() string {
	if x != nil {
		return x.WorkspaceName
	}
	return ""
}

func (x *RegisterUserToWorkspaceRequest) GetWorkspaceOwnerUsername() string {
	if x != nil {
		return x.WorkspaceOwnerUsername
	}
	return ""
}

type RegisterUserToWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserToWorkspaceResponse) Reset() {
	*x = RegisterUserToWorkspaceResponse{}
	mi := &file_proto_cli_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserToWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserToWorkspaceResponse) ProtoMessage() {}

func (x *RegisterUserToWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserToWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserToWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{5}
}

type RequestPunchFromReceiverRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ListenerUsername       string                 `protobuf:"bytes,1,opt,name=listener_username,json=listenerUsername,proto3" json:"listener_username,omitempty"`
	ListenerPassword       string                 `protobuf:"bytes,2,opt,name=listener_password,json=listenerPassword,proto3" json:"listener_password,omitempty"`
	ListenerPublicIp       string                 `protobuf:"bytes,3,opt,name=listener_public_ip,json=listenerPublicIp,proto3" json:"listener_public_ip,omitempty"`
	ListenerPublicPort     string                 `protobuf:"bytes,4,opt,name=listener_public_port,json=listenerPublicPort,proto3" json:"listener_public_port,omitempty"`
	WorkspaceOwnerUsername string                 `protobuf:"bytes,5,opt,name=workspace_owner_username,json=workspaceOwnerUsername,proto3" json:"workspace_owner_username,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RequestPunchFromReceiverRequest) Reset() {
	*x = RequestPunchFromReceiverRequest{}
	mi := &file_proto_cli_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPunchFromReceiverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPunchFromReceiverRequest) ProtoMessage() {}

func (x *RequestPunchFromReceiverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPunchFromReceiverRequest.ProtoReflect.Descriptor instead.
func (*RequestPunchFromReceiverRequest) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{6}
}

func (x *RequestPunchFromReceiverRequest) GetListenerUsername() string {
	if x != nil {
		return x.ListenerUsername
	}
	return ""
}

func (x *RequestPunchFromReceiverRequest) GetListenerPassword() string {
	if x != nil {
		return x.ListenerPassword
	}
	return ""
}

func (x *RequestPunchFromReceiverRequest) GetListenerPublicIp() string {
	if x != nil {
		return x.ListenerPublicIp
	}
	return ""
}

func (x *RequestPunchFromReceiverRequest) GetListenerPublicPort() string {
	if x != nil {
		return x.ListenerPublicPort
	}
	return ""
}

func (x *RequestPunchFromReceiverRequest) GetWorkspaceOwnerUsername() string {
	if x != nil {
		return x.WorkspaceOwnerUsername
	}
	return ""
}

type RequestPunchFromReceiverResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceOwnerPublicIp   string                 `protobuf:"bytes,1,opt,name=workspace_owner_public_ip,json=workspaceOwnerPublicIp,proto3" json:"workspace_owner_public_ip,omitempty"`
	WorkspaceOwnerPublicPort string                 `protobuf:"bytes,2,opt,name=workspace_owner_public_port,json=workspaceOwnerPublicPort,proto3" json:"workspace_owner_public_port,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RequestPunchFromReceiverResponse) Reset() {
	*x = RequestPunchFromReceiverResponse{}
	mi := &file_proto_cli_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPunchFromReceiverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPunchFromReceiverResponse) ProtoMessage() {}

func (x *RequestPunchFromReceiverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPunchFromReceiverResponse.ProtoReflect.Descriptor instead.
func (*RequestPunchFromReceiverResponse) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{7}
}

func (x *RequestPunchFromReceiverResponse) GetWorkspaceOwnerPublicIp() string {
	if x != nil {
		return x.WorkspaceOwnerPublicIp
	}
	return ""
}

func (x *RequestPunchFromReceiverResponse) GetWorkspaceOwnerPublicPort() string {
	if x != nil {
		return x.WorkspaceOwnerPublicPort
	}
	return ""
}

type NotifyNewPushToListenersRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceOwnerUsername string                 `protobuf:"bytes,1,opt,name=workspace_owner_username,json=workspaceOwnerUsername,proto3" json:"workspace_owner_username,omitempty"`
	WorkspaceOwnerPassword string                 `protobuf:"bytes,2,opt,name=workspace_owner_password,json=workspaceOwnerPassword,proto3" json:"workspace_owner_password,omitempty"`
	WorkspaceName          string                 `protobuf:"bytes,3,opt,name=workspace_name,json=workspaceName,proto3" json:"workspace_name,omitempty"`
	NewWorkspaceHash       string                 `protobuf:"bytes,4,opt,name=new_workspace_hash,json=newWorkspaceHash,proto3" json:"new_workspace_hash,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NotifyNewPushToListenersRequest) Reset() {
	*x = NotifyNewPushToListenersRequest{}
	mi := &file_proto_cli_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNewPushToListenersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewPushToListenersRequest) ProtoMessage() {}

func (x *NotifyNewPushToListenersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewPushToListenersRequest.ProtoReflect.Descriptor instead.
func (*NotifyNewPushToListenersRequest) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{8}
}

func (x *NotifyNewPushToListenersRequest) GetWorkspaceOwnerUsername() string {
	if x != nil {
		return x.WorkspaceOwnerUsername
	}
	return ""
}

func (x *NotifyNewPushToListenersRequest) GetWorkspaceOwnerPassword() string {
	if x != nil {
		return x.WorkspaceOwnerPassword
	}
	return ""
}

func (x *NotifyNewPushToListenersRequest) GetWorkspaceName() string {
	if x != nil {
		return x.WorkspaceName
	}
	return ""
}

func (x *NotifyNewPushToListenersRequest) GetNewWorkspaceHash() string {
	if x != nil {
		return x.NewWorkspaceHash
	}
	return ""
}

type NotifyNewPushToListenersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNewPushToListenersResponse) Reset() {
	*x = NotifyNewPushToListenersResponse{}
	mi := &file_proto_cli_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNewPushToListenersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewPushToListenersResponse) ProtoMessage() {}

func (x *NotifyNewPushToListenersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewPushToListenersResponse.ProtoReflect.Descriptor instead.
func (*NotifyNewPushToListenersResponse) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{9}
}

type GetAllWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllWorkspacesRequest) Reset() {
	*x = GetAllWorkspacesRequest{}
	mi := &file_proto_cli_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllWorkspacesRequest) ProtoMessage() {}

func (x *GetAllWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*GetAllWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllWorkspacesRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetAllWorkspacesRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type WorkspaceInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceOwner string                 `protobuf:"bytes,1,opt,name=workspace_owner,json=workspaceOwner,proto3" json:"workspace_owner,omitempty"`
	WorkspaceName  string                 `protobuf:"bytes,2,opt,name=workspace_name,json=workspaceName,proto3" json:"workspace_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkspaceInfo) Reset() {
	*x = WorkspaceInfo{}
	mi := &file_proto_cli_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceInfo) ProtoMessage() {}

func (x *WorkspaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceInfo.ProtoReflect.Descriptor instead.
func (*WorkspaceInfo) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{11}
}

func (x *WorkspaceInfo) GetWorkspaceOwner() string {
	if x != nil {
		return x.WorkspaceOwner
	}
	return ""
}

func (x *WorkspaceInfo) GetWorkspaceName() string {
	if x != nil {
		return x.WorkspaceName
	}
	return ""
}

type GetAllWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*WorkspaceInfo       `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllWorkspacesResponse) Reset() {
	*x = GetAllWorkspacesResponse{}
	mi := &file_proto_cli_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllWorkspacesResponse) ProtoMessage() {}

func (x *GetAllWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*GetAllWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllWorkspacesResponse) GetWorkspaces() []*WorkspaceInfo {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type GetLastHashOfWorkspaceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceOwner   string                 `protobuf:"bytes,1,opt,name=workspace_owner,json=workspaceOwner,proto3" json:"workspace_owner,omitempty"`
	WorkspaceName    string                 `protobuf:"bytes,2,opt,name=workspace_name,json=workspaceName,proto3" json:"workspace_name,omitempty"`
	ListenerUsername string                 `protobuf:"bytes,3,opt,name=listener_username,json=listenerUsername,proto3" json:"listener_username,omitempty"`
	ListenerPassword string                 `protobuf:"bytes,4,opt,name=listener_password,json=listenerPassword,proto3" json:"listener_password,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetLastHashOfWorkspaceRequest) Reset() {
	*x = GetLastHashOfWorkspaceRequest{}
	mi := &file_proto_cli_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastHashOfWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastHashOfWorkspaceRequest) ProtoMessage() {}

func (x *GetLastHashOfWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastHashOfWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetLastHashOfWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{13}
}

func (x *GetLastHashOfWorkspaceRequest) GetWorkspaceOwner() string {
	if x != nil {
		return x.WorkspaceOwner
	}
	return ""
}

func (x *GetLastHashOfWorkspaceRequest) GetWorkspaceName() string {
	if x != nil {
		return x.WorkspaceName
	}
	return ""
}

func (x *GetLastHashOfWorkspaceRequest) GetListenerUsername() string {
	if x != nil {
		return x.ListenerUsername
	}
	return ""
}

func (x *GetLastHashOfWorkspaceRequest) GetListenerPassword() string {
	if x != nil {
		return x.ListenerPassword
	}
	return ""
}

type GetLastHashOfWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastHash      string                 `protobuf:"bytes,1,opt,name=last_hash,json=lastHash,proto3" json:"last_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastHashOfWorkspaceResponse) Reset() {
	*x = GetLastHashOfWorkspaceResponse{}
	mi := &file_proto_cli_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastHashOfWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastHashOfWorkspaceResponse) ProtoMessage() {}

func (x *GetLastHashOfWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastHashOfWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*GetLastHashOfWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_cli_proto_rawDescGZIP(), []int{14}
}

func (x *GetLastHashOfWorkspaceResponse) GetLastHash() string {
	if x != nil {
		return x.LastHash
	}
	return ""
}

var File_proto_cli_proto protoreflect.FileDescriptor

const file_proto_cli_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/cli.proto\x12\x05proto\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x12\n" +
	"\x10RegisterResponse\"\x96\x01\n" +
	"\x18RegisterWorkspaceRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12%\n" +
	"\x0eworkspace_name\x18\x03 \x01(\tR\rworkspaceName\x12\x1b\n" +
	"\tlast_hash\x18\x04 \x01(\tR\blastHash\"\x1b\n" +
	"\x19RegisterWorkspaceResponse\"\xdb\x01\n" +
	"\x1eRegisterUserToWorkspaceRequest\x12+\n" +
	"\x11listener_username\x18\x01 \x01(\tR\x10listenerUsername\x12+\n" +
	"\x11listener_password\x18\x02 \x01(\tR\x10listenerPassword\x12%\n" +
	"\x0eworkspace_name\x18\x03 \x01(\tR\rworkspaceName\x128\n" +
	"\x18workspace_owner_username\x18\x04 \x01(\tR\x16workspaceOwnerUsername\"!\n" +
	"\x1fRegisterUserToWorkspaceResponse\"\x95\x02\n" +
	"\x1fRequestPunchFromReceiverRequest\x12+\n" +
	"\x11listener_username\x18\x01 \x01(\tR\x10listenerUsername\x12+\n" +
	"\x11listener_password\x18\x02 \x01(\tR\x10listenerPassword\x12,\n" +
	"\x12listener_public_ip\x18\x03 \x01(\tR\x10listenerPublicIp\x120\n" +
	"\x14listener_public_port\x18\x04 \x01(\tR\x12listenerPublicPort\x128\n" +
	"\x18workspace_owner_username\x18\x05 \x01(\tR\x16workspaceOwnerUsername\"\x9c\x01\n" +
	" RequestPunchFromReceiverResponse\x129\n" +
	"\x19workspace_owner_public_ip\x18\x01 \x01(\tR\x16workspaceOwnerPublicIp\x12=\n" +
	"\x1bworkspace_owner_public_port\x18\x02 \x01(\tR\x18workspaceOwnerPublicPort\"\xea\x01\n" +
	"\x1fNotifyNewPushToListenersRequest\x128\n" +
	"\x18workspace_owner_username\x18\x01 \x01(\tR\x16workspaceOwnerUsername\x128\n" +
	"\x18workspace_owner_password\x18\x02 \x01(\tR\x16workspaceOwnerPassword\x12%\n" +
	"\x0eworkspace_name\x18\x03 \x01(\tR\rworkspaceName\x12,\n" +
	"\x12new_workspace_hash\x18\x04 \x01(\tR\x10newWorkspaceHash\"\"\n" +
	" NotifyNewPushToListenersResponse\"Q\n" +
	"\x17GetAllWorkspacesRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"_\n" +
	"\rWorkspaceInfo\x12'\n" +
	"\x0fworkspace_owner\x18\x01 \x01(\tR\x0eworkspaceOwner\x12%\n" +
	"\x0eworkspace_name\x18\x02 \x01(\tR\rworkspaceName\"P\n" +
	"\x18GetAllWorkspacesResponse\x124\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x14.proto.WorkspaceInfoR\n" +
	"workspaces\"\xc9\x01\n" +
	"\x1dGetLastHashOfWorkspaceRequest\x12'\n" +
	"\x0fworkspace_owner\x18\x01 \x01(\tR\x0eworkspaceOwner\x12%\n" +
	"\x0eworkspace_name\x18\x02 \x01(\tR\rworkspaceName\x12+\n" +
	"\x11listener_username\x18\x03 \x01(\tR\x10listenerUsername\x12+\n" +
	"\x11listener_password\x18\x04 \x01(\tR\x10listenerPassword\"=\n" +
	"\x1eGetLastHashOfWorkspaceResponse\x12\x1b\n" +
	"\tlast_hash\x18\x01 \x01(\tR\blastHash2\xaf\x05\n" +
	"\n" +
	"CliService\x12=\n" +
	"\bRegister\x12\x16.proto.RegisterRequest\x1a\x17.proto.RegisterResponse\"\x00\x12X\n" +
	"\x11RegisterWorkspace\x12\x1f.proto.RegisterWorkspaceRequest\x1a .proto.RegisterWorkspaceResponse\"\x00\x12j\n" +
	"\x17RegisterUserToWorkspace\x12%.proto.RegisterUserToWorkspaceRequest\x1a&.proto.RegisterUserToWorkspaceResponse\"\x00\x12m\n" +
	"\x18RequestPunchFromReceiver\x12&.proto.RequestPunchFromReceiverRequest\x1a'.proto.RequestPunchFromReceiverResponse\"\x00\x12m\n" +
	"\x18NotifyNewPushToListeners\x12&.proto.NotifyNewPushToListenersRequest\x1a'.proto.NotifyNewPushToListenersResponse\"\x00\x12U\n" +
	"\x10GetAllWorkspaces\x12\x1e.proto.GetAllWorkspacesRequest\x1a\x1f.proto.GetAllWorkspacesResponse\"\x00\x12g\n" +
	"\x16GetLastHashOfWorkspace\x12$.proto.GetLastHashOfWorkspaceRequest\x1a%.proto.GetLastHashOfWorkspaceResponse\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_cli_proto_rawDescOnce sync.Once
	file_proto_cli_proto_rawDescData []byte
)

func file_proto_cli_proto_rawDescGZIP() []byte {
	file_proto_cli_proto_rawDescOnce.Do(func() {
		file_proto_cli_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cli_proto_rawDesc), len(file_proto_cli_proto_rawDesc)))
	})
	return file_proto_cli_proto_rawDescData
}

var file_proto_cli_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_cli_proto_goTypes = []any{
	(*RegisterRequest)(nil),                  // 0: proto.RegisterRequest
	(*RegisterResponse)(nil),                 // 1: proto.RegisterResponse
	(*RegisterWorkspaceRequest)(nil),         // 2: proto.RegisterWorkspaceRequest
	(*RegisterWorkspaceResponse)(nil),        // 3: proto.RegisterWorkspaceResponse
	(*RegisterUserToWorkspaceRequest)(nil),   // 4: proto.RegisterUserToWorkspaceRequest
	(*RegisterUserToWorkspaceResponse)(nil),  // 5: proto.RegisterUserToWorkspaceResponse
	(*RequestPunchFromReceiverRequest)(nil),  // 6: proto.RequestPunchFromReceiverRequest
	(*RequestPunchFromReceiverResponse)(nil), // 7: proto.RequestPunchFromReceiverResponse
	(*NotifyNewPushToListenersRequest)(nil),  // 8: proto.NotifyNewPushToListenersRequest
	(*NotifyNewPushToListenersResponse)(nil), // 9: proto.NotifyNewPushToListenersResponse
	(*GetAllWorkspacesRequest)(nil),          // 10: proto.GetAllWorkspacesRequest
	(*WorkspaceInfo)(nil),                    // 11: proto.WorkspaceInfo
	(*GetAllWorkspacesResponse)(nil),         // 12: proto.GetAllWorkspacesResponse
	(*GetLastHashOfWorkspaceRequest)(nil),    // 13: proto.GetLastHashOfWorkspaceRequest
	(*GetLastHashOfWorkspaceResponse)(nil),   // 14: proto.GetLastHashOfWorkspaceResponse
}
var file_proto_cli_proto_depIdxs = []int32{
	11, // 0: proto.GetAllWorkspacesResponse.workspaces:type_name -> proto.WorkspaceInfo
	0,  // 1: proto.CliService.Register:input_type -> proto.RegisterRequest
	2,  // 2: proto.CliService.RegisterWorkspace:input_type -> proto.RegisterWorkspaceRequest
	4,  // 3: proto.CliService.RegisterUserToWorkspace:input_type -> proto.RegisterUserToWorkspaceRequest
	6,  // 4: proto.CliService.RequestPunchFromReceiver:input_type -> proto.RequestPunchFromReceiverRequest
	8,  // 5: proto.CliService.NotifyNewPushToListeners:input_type -> proto.NotifyNewPushToListenersRequest
	10, // 6: proto.CliService.GetAllWorkspaces:input_type -> proto.GetAllWorkspacesRequest
	13, // 7: proto.CliService.GetLastHashOfWorkspace:input_type -> proto.GetLastHashOfWorkspaceRequest
	1,  // 8: proto.CliService.Register:output_type -> proto.RegisterResponse
	3,  // 9: proto.CliService.RegisterWorkspace:output_type -> proto.RegisterWorkspaceResponse
	5,  // 10: proto.CliService.RegisterUserToWorkspace:output_type -> proto.RegisterUserToWorkspaceResponse
	7,  // 11: proto.CliService.RequestPunchFromReceiver:output_type -> proto.RequestPunchFromReceiverResponse
	9,  // 12: proto.CliService.NotifyNewPushToListeners:output_type -> proto.NotifyNewPushToListenersResponse
	12, // 13: proto.CliService.GetAllWorkspaces:output_type -> proto.GetAllWorkspacesResponse
	14, // 14: proto.CliService.GetLastHashOfWorkspace:output_type -> proto.GetLastHashOfWorkspaceResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_cli_proto_init() }
func file_proto_cli_proto_init() {
	if File_proto_cli_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cli_proto_rawDesc), len(file_proto_cli_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cli_proto_goTypes,
		DependencyIndexes: file_proto_cli_proto_depIdxs,
		MessageInfos:      file_proto_cli_proto_msgTypes,
	}.Build()
	File_proto_cli_proto = out.File
	file_proto_cli_proto_goTypes = nil
	file_proto_cli_proto_depIdxs = nil
}
